### ISSUE TITLE
The "unsaved" text is very small

### ISSUE THREAD

**Issue by mathlord2** [swecc-uw/pairing-client#6]
The "unsaved" text on the "Mock Interview Sign Up" page (i.e. selecting your available times) is hard to see and is too close to the button. Make it bigger and add a margin between it and the button :)

![small-unsaved](https://github.com/swecc-uw/pairing-client/assets/42785168/09a532b2-788f-41c5-9234-8d94133d34de)

**Comment by elimelt** [comment]
Solved 🫡
